#!/bin/bash
cd /home/richard/development/raku-collection-raku-documentation/Website
sass "scss/pod.scss":"templates/pod.css"
sass "plugins/website/website-styling.scss":"plugins/website/website-div-styling.css"